### ISSUE TITLE
New keybindings?

### ISSUE THREAD

**Issue by bjartwolf** [kofno/purescript-spacemacs#1]
I am trying out the package, it seems like keybindings have changed for example SPC - m s i for the PSCI, not SPC m p p as it says in the documentation. I'm so new to spacemacs/emacs and purescript I am not sure if this is something I've done or if the keybindings have changed.

**Comment by kofno** [comment]
Hi!

This repo is a bit of a legacy. I was using this until my work was merged into spacemacs proper. During that process, the keybindings and such were changed to be more inline with what the spacemacs project wanted. 

The current documentation is here: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/purescript

**Comment by bjartwolf** [comment]
Got it, thanks!
