### ISSUE TITLE
PSCI quitting when loading modules

### ISSUE THREAD

**Issue by bjartwolf** [kofno/purescript-spacemacs#2]
I am trying to start with a simple .psci file generated by npm run psci in the following repo which is more or less the tutorial on purescript https://github.com/bjartwolf/playwithps

If I open the PSCI from spacemacs (SPC m s i) and then try to load the euler file or the psci project (SPC m s b or SPC m s p) the PSCI console just ends in "See ya! and Process finished".

When starting psci from console everything works fine, it loads the project files automatically and Euler.answer is there with autocomplete etc.

**Comment by kofno** [comment]
Hrm... that seems like a problem with the psci plugin. Have you checked to see if this issue is related to what you are seeing?

https://github.com/ardumont/emacs-psci/issues/9

**Comment by bjartwolf** [comment]
Thanks, it probably is, I guess I can close this issue. Tried that patch but it didn't help me, but at least I know which repo to look at...

**Comment by kofno** [comment]
My pleasure. Sorry I couldn't be more help, but that thanks for checking in :)
