### ISSUE TITLE
error in process sentinel: json-read

### ISSUE THREAD

**Issue by AveryLychee** [kofno/purescript-spacemacs#3]
I have a fresh install of purescript and just added this to my spacemacs, but whenever I open a `.purs` file, I get this error repeatedly:

```
error in process sentinel: json-read: End of file while parsing JSON
error in process sentinel: End of file while parsing JSON
```

versions:
```
Pulp version 12.3.0
purs version 0.12.0 [development build; commit: UNKNOWN] using /home/avery/.nix-profile/bin/purs
```

**Comment by kofno** [comment]
The official purescript layer is now in the purescript project --> https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/purescript

Make sure that is the layer you are using and then open any issues you have in that repo.
